name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Test app startup
        run: |
          python -c "from src import pearbot; print('pearbot module imported successfully')"
          python -m src.pearbot --help
        env:
          GITHUB_APP_ID: dummy_id
          GITHUB_PRIVATE_KEY: dummy_key
          GITHUB_APP_WEBHOOK_SECRET: dummy_secret

      - name: Test server startup
        run: |
          timeout 5s python -m src.pearbot --server || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
        env:
          GITHUB_APP_ID: dummy_id
          GITHUB_PRIVATE_KEY: dummy_key
          GITHUB_APP_WEBHOOK_SECRET: dummy_secret
