name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Test app startup
      run: |
        python -c "import main; print('Main module imported successfully')"
        python main.py --help
      env:
        GITHUB_APP_ID: dummy_id
        GITHUB_PRIVATE_KEY: dummy_key
        GITHUB_APP_WEBHOOK_SECRET: dummy_secret

    - name: Test server startup
      run: |
        timeout 5s python main.py --server || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
      env:
        GITHUB_APP_ID: dummy_id
        GITHUB_PRIVATE_KEY: dummy_key
        GITHUB_APP_WEBHOOK_SECRET: dummy_secret
